// Reuse the measured synthetic/source input reader, not its static fit results.
#define main garment_geometry_reference_main
#include "garment_test.cpp"
#undef main
bool ClothRun(){
 auto input=Fixture();input.deltaTime=0;Session gravity,weightless;auto rest=gravity.Update(Style::WhiteJockstrap,input);auto zero=input;zero.gravity={};weightless.Update(Style::WhiteJockstrap,zero);
 double maxStretch=0,maxGap=0,total=0;for(unsigned i=0;i<120;i++){input.deltaTime=zero.deltaTime=1./120;auto& out=gravity.Update(Style::WhiteJockstrap,input);weightless.Update(Style::WhiteJockstrap,zero);maxStretch=std::max(maxStretch,out.physics.maxStretchRatio);maxGap=std::max(maxGap,out.physics.maxSeamGap);total+=out.physics.solverMilliseconds;if(!out.contactBudgetSatisfied||!out.physics.materialBudgetSatisfied){std::cerr<<"physics step "<<i<<" stretch "<<out.physics.maxStretchRatio<<" gap "<<out.physics.maxSeamGap<<" coverage "<<out.coverageMargin<<" contact "<<out.contactBudgetSatisfied<<" maxdisp "<<out.physics.maxDisplacement<<"\n";Export(out,"build/cloth-failed.obj");Export(rest,"build/cloth-rest.obj");return false;}}
 auto out=gravity.Update(Style::WhiteJockstrap,Input(input));double difference=0;auto& flat=weightless.Update(Style::WhiteJockstrap,zero);for(unsigned i=0;i<out.mesh.vertices.size();i++)difference=std::max(difference,Length(Sub(out.mesh.vertices[i].position,flat.mesh.vertices[i].position)));
 Export(out,"build/cloth-steady.obj");REQUIRE(difference>1e-5);REQUIRE(out.physics.stateReady&&out.physics.active&&out.physics.nodes>0&&out.physics.constraints>out.physics.nodes);REQUIRE(std::abs(out.physics.accumulatedSeconds-121./120)<1e-10);std::cout<<"PASS sag/gravity delta="<<difference<<" stretch="<<maxStretch<<" gap="<<maxGap<<" meanMs="<<total/120<<"\n";
 return true;
}
bool Timing(){auto input=Fixture();input.deltaTime=0;Session sixty,thirty,oneTwenty;sixty.Update(Style::WhiteJockstrap,input);thirty.Update(Style::WhiteJockstrap,input);oneTwenty.Update(Style::WhiteJockstrap,input);for(unsigned i=0;i<120;i++){input.deltaTime=1./120;oneTwenty.Update(Style::WhiteJockstrap,input);if(i%2==0){input.deltaTime=1./60;sixty.Update(Style::WhiteJockstrap,input);}if(i%4==0){input.deltaTime=1./30;thirty.Update(Style::WhiteJockstrap,input);}}input.deltaTime=0;auto a=sixty.Update(Style::WhiteJockstrap,input),b=thirty.Update(Style::WhiteJockstrap,input),c=oneTwenty.Update(Style::WhiteJockstrap,input);double error=0;for(unsigned i=0;i<a.mesh.vertices.size();i++)error=std::max({error,Length(Sub(a.mesh.vertices[i].position,b.mesh.vertices[i].position)),Length(Sub(a.mesh.vertices[i].position,c.mesh.vertices[i].position))});std::cout<<"TIME partition error="<<error<<"\n";REQUIRE(error<2e-5*a.measuredCircumference);return true;}
bool CovariantDynamics(){auto in=Fixture();Session a,b;auto scaled=in;scaled.gravity=Mul(in.gravity,100);Point shift{1000,-900,800};scaled.frame.origin=shift;for(auto* samples:{&scaled.waist,&scaled.opening,&scaled.anatomy,&scaled.rearStraps[0],&scaled.rearStraps[1]})for(auto& s:*samples)s.position=Add(Mul(s.position,100),shift);for(unsigned frame=0;frame<30;frame++){auto x=a.Update(Style::WhiteJockstrap,in),y=b.Update(Style::WhiteJockstrap,scaled);for(unsigned i=0;i<x.mesh.vertices.size();i++)REQUIRE(Length(Sub(Add(Mul(x.mesh.vertices[i].position,100),shift),y.mesh.vertices[i].position))<1e-7);REQUIRE(x.physics.materialBudgetSatisfied&&y.physics.materialBudgetSatisfied);}std::cout<<"PASS persistent translation/unit covariance\n";return true;}
bool Lifecycle(){auto in=Fixture();Session s;auto first=s.Update(Style::WhiteJockstrap,in);REQUIRE(first.physics.reset);auto before=s.Update(Style::WhiteJockstrap,in);in.deltaTime=0;auto paused=s.Update(Style::WhiteJockstrap,in);REQUIRE(paused.physics.advancedSeconds==0&&paused.physics.accumulatedSeconds==before.physics.accumulatedSeconds);in.restRevision++;for(auto& point:in.anatomy)point.position[1]+=.04;auto enlarged=s.Update(Style::WhiteJockstrap,in);REQUIRE(enlarged.physics.stateReady&&!enlarged.physics.reset&&enlarged.mesh.vertices.size()==paused.mesh.vertices.size());in.characterEpoch++;auto epoch=s.Update(Style::WhiteJockstrap,in);REQUIRE(epoch.physics.reset&&epoch.physics.accumulatedSeconds==0);in.deltaTime=1.1;auto discontinuity=s.Update(Style::WhiteJockstrap,in);REQUIRE(discontinuity.physics.reset&&discontinuity.physics.advancedSeconds==0);auto naked=s.Update(Style::Naked,in);REQUIRE(naked.mesh.vertices.empty()&&!naked.physics.stateReady);std::cout<<"PASS paused time, scale rest revision, epoch/Naked/discontinuity reset\n";return true;}
int main(int argc,char** argv){try{if(argc>1){auto in=LoadFixture(argv[1]);in.deltaTime=0;Session s;s.Update(Style::WhiteJockstrap,in);for(unsigned i=0;i<60;i++){in.deltaTime=1./60;auto& out=s.Update(Style::WhiteJockstrap,in);std::cout<<i<<" ms="<<out.physics.solverMilliseconds<<" stretch="<<out.physics.maxStretchRatio<<" seam="<<out.physics.maxSeamGap<<" coverage="<<out.coverageMargin<<" contact="<<out.contactBudgetSatisfied<<" material="<<out.physics.materialBudgetSatisfied<<"\n";if(argc>2&&i==59)Export(out,argv[2]);if(!out.physics.materialBudgetSatisfied||!out.contactBudgetSatisfied)return 1;}return 0;}return ClothRun()&&Timing()&&CovariantDynamics()&&Lifecycle()?0:1;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 2;}}
