#include <malemod/garments/jockstrap.hpp>
#include "garment_shape_checks.hpp"
#include <chrono>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <string>
using namespace malemod::garments;
#define REQUIRE(x) do{if(!(x)){std::cerr<<"FAIL "<<__LINE__<<": "<<#x<<'\n';return false;}}while(0)
Sample S(Point p,Point n,Surface surface,unsigned index){Sample s{p,n,{}};s.lineage.donors[0]={surface,index,1};return s;}
Input Fixture(double scale=1,double phase=0,unsigned resolution=32){
    Input in;in.characterEpoch=1;in.topologyRevision=1;in.gravity={0,0,-9.81};in.deltaTime=1./60;
    for(unsigned i=0;i<48;i++){double t=detail::pi*2*i/48;in.waist.push_back(S({.22*std::cos(t),.155*std::sin(t),1.16},{std::cos(t),std::sin(t),0},Surface::Body,i));}
    for(unsigned i=0;i<32;i++){double t=detail::pi*2*i/32;in.opening.push_back(S({.075*std::cos(t),.125,.815+.105*std::sin(t)},{0,1,0},Surface::Body,48+i));}
    auto ellipsoid=[&](Point center,Point radius,unsigned rings){unsigned base=unsigned(in.anatomy.size());for(unsigned j=0;j<=rings;j++)for(unsigned i=0;i<=resolution;i++){double p=detail::pi*(j+.01)/(rings+.02),t=detail::pi*2*(i%resolution)/resolution;Point n{std::sin(p)*std::cos(t),std::sin(p)*std::sin(t),std::cos(p)};auto point=Add(center,{n[0]*radius[0],n[1]*radius[1],n[2]*radius[2]});in.anatomy.push_back(S(point,n,Surface::Anatomy,unsigned(in.anatomy.size())));}for(unsigned j=0;j<rings;j++)for(unsigned i=0;i<resolution;i++){unsigned a=base+j*(resolution+1)+i;in.anatomyTriangles.push_back({a,a+1,a+resolution+2});in.anatomyTriangles.push_back({a,a+resolution+2,a+resolution+1});}};
    ellipsoid({.035*std::sin(phase)*scale,.15+.12*scale,.845+.04*std::sin(phase*.8)*scale},{.042*scale,.155*scale,.043*scale},resolution);
    for(double sign:{-1.,1.})ellipsoid({sign*.062*scale,.16,.724-.025*std::cos(phase)*scale},{.06*scale,.055*scale,.082*scale},resolution/2);
    for(unsigned side=0;side<2;side++){double s=side?1:-1;in.rearStraps[side]={S({s*.15,-.13,1.12},{s*.7,-.7,0},Surface::Body,side),S({s*.16,-.17,.87},{s*.5,-.5,-.7},Surface::Body,side+2),S({s*.13,-.04,.70},{s*.5,0,-.8},Surface::Body,side+4),S({s*.065,.13,.725},{0,1,0},Surface::Body,side+6)};}
    return in;
}
bool Valid(const Output& out){REQUIRE(!out.mesh.vertices.empty());REQUIRE(out.mesh.vertices.size()<65536);REQUIRE(out.coverageMargin>0);bool materials[4]{};for(const auto& t:out.mesh.triangles){materials[unsigned(t.material)]=true;for(auto i:t.vertices)REQUIRE(i<out.mesh.vertices.size());}for(bool used:materials)REQUIRE(used);for(const auto& v:out.mesh.vertices){REQUIRE(Finite(v.position)&&Finite(v.normal)&&Finite(v.tangent));REQUIRE(std::abs(Length(v.normal)-1)<1e-8&&std::abs(Length(v.tangent)-1)<1e-8&&std::abs(Dot(v.normal,v.tangent))<1e-8);REQUIRE(v.tangentSign==1||v.tangentSign==-1);double sum=0;for(const auto& d:v.lineage.donors)sum+=d.weight;REQUIRE(std::abs(sum-1)<1e-8);}REQUIRE(out.support.size()<=64);return true;}
bool Stress(){Session session;double worst=0,total=0;std::size_t vertexCount=0,capacity=0;for(unsigned i=0;i<240;i++){double scale=1+11*(.5+.5*std::sin(i*.19));auto input=Fixture(scale,i*.16);auto begin=std::chrono::steady_clock::now();const auto& out=session.Update(Style::WhiteJockstrap,input);double ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count();worst=std::max(worst,ms);total+=ms;REQUIRE(Valid(out));garment_shape::Measure(input,out);REQUIRE(out.contactBudgetSatisfied);if(!i){vertexCount=out.mesh.vertices.size();capacity=out.mesh.vertices.capacity();}else{REQUIRE(vertexCount==out.mesh.vertices.size());REQUIRE(capacity==out.mesh.vertices.capacity());}}
    auto giant=Fixture(40,.4,96);giant.topologyRevision=2;const auto& out=session.Update(Style::WhiteJockstrap,giant);REQUIRE(Valid(out));REQUIRE(out.measuredCircumference>1);auto& naked=session.Update(Style::Naked,giant);REQUIRE(naked.mesh.vertices.empty()&&naked.mesh.triangles.empty()&&naked.support.empty());session.Reset();REQUIRE(Valid(session.Update(Style::WhiteJockstrap,Fixture())));std::cout<<"PASS 240 animated 1..12x surfaces +40x dense extreme, fixed topology/capacity, Naked/reset, mean "<<total/240<<"ms worst "<<worst<<"ms\n";REQUIRE(total/240<30);return true;}
bool Collision(){Session session;auto in=Fixture();in.bodyContacts.push_back({{.19,-.03,.70},{.19,.16,.70},.045});const auto& out=session.Update(Style::WhiteJockstrap,in);REQUIRE(Valid(out));garment_shape::Measure(in,out);REQUIRE(out.projectedContacts>0);if(!out.contactBudgetSatisfied){double minimum=1e100;unsigned bad=0;for(unsigned i=0;i<out.mesh.vertices.size();i++){double d=detail::CapsuleDistance(out.mesh.vertices[i].position,in.bodyContacts[0]);if(d<minimum){minimum=d;bad=i;}}std::cerr<<"CONTACT min "<<minimum<<" vertex "<<bad<<" target "<<out.measuredCircumference*.008*.3<<"\n";}REQUIRE(out.contactBudgetSatisfied);for(const auto& v:out.mesh.vertices)REQUIRE(detail::CapsuleDistance(v.position,in.bodyContacts[0])>=out.measuredCircumference*.008*.3-1e-8);for(const auto& t:out.mesh.triangles){Point cloth,axis;REQUIRE(detail::TriangleCapsule(out.mesh.vertices[t.vertices[0]].position,out.mesh.vertices[t.vertices[1]].position,out.mesh.vertices[t.vertices[2]].position,in.bodyContacts[0],cloth,axis,out.measuredCircumference*.008*.3)>=out.measuredCircumference*.008*.3-1e-8);}Point cloth,axis;Capsule crossing{{0,0,-1},{0,0,1},.1};REQUIRE(detail::TriangleCapsule({-2,-2,0},{2,-2,0},{0,2,0},crossing,cloth,axis)<0);std::cout<<"PASS body-volume contact projection with positive anatomical coverage\n";return true;}
bool Covariance(){Session a,b;auto in=Fixture(7,.8);const auto& first=a.Update(Style::WhiteJockstrap,in);auto shifted=in;Point offset{50,-30,12};shifted.frame.origin=offset;for(auto* samples:{&shifted.waist,&shifted.opening,&shifted.anatomy,&shifted.rearStraps[0],&shifted.rearStraps[1]})for(auto& p:*samples)p.position=Add(p.position,offset);const auto& second=b.Update(Style::WhiteJockstrap,shifted);REQUIRE(first.mesh.vertices.size()==second.mesh.vertices.size());for(unsigned i=0;i<first.mesh.vertices.size();i++){auto error=Length(Sub(Add(first.mesh.vertices[i].position,offset),second.mesh.vertices[i].position));if(error>=1e-10)std::cerr<<"COVARIANCE vertex="<<i<<" error="<<error<<"\n";REQUIRE(error<1e-10);}auto unitScaled=in;unitScaled.frame.origin=Mul(in.frame.origin,100);unitScaled.gravity=Mul(in.gravity,100);for(auto* samples:{&unitScaled.waist,&unitScaled.opening,&unitScaled.anatomy,&unitScaled.rearStraps[0],&unitScaled.rearStraps[1]})for(auto& p:*samples)p.position=Mul(p.position,100);Session c;const auto& third=c.Update(Style::WhiteJockstrap,unitScaled);for(unsigned i=0;i<first.mesh.vertices.size();i++)REQUIRE(Length(Sub(Mul(first.mesh.vertices[i].position,100),third.mesh.vertices[i].position))<1e-8);std::cout<<"PASS translation and explicit unit covariance\n";return true;}
bool Rejection(){Session s;for(unsigned mode=0;mode<5;mode++){auto in=Fixture();if(mode==0)in.frame.forward={0,0,1};if(mode==1)in.anatomy[0].position[0]=std::nan("");if(mode==2)in.waist[0].lineage.donors[0].weight=0;if(mode==3)in.bodyContacts.resize(65);if(mode==4)in.anatomyTriangles.push_back({999999,0,1});bool rejected=false;try{s.Update(Style::WhiteJockstrap,in);}catch(const std::invalid_argument&){rejected=true;}REQUIRE(rejected);}std::cout<<"PASS malformed frame, surface, lineage, contact budget and topology rejection\n";return true;}
void Export(const Output& o,const char* path){std::ofstream f(path);f<<"mtllib jockstrap.mtl\n"<<std::setprecision(12);for(const auto& v:o.mesh.vertices)f<<"v "<<v.position[0]<<' '<<v.position[1]<<' '<<v.position[2]<<'\n';for(const auto& v:o.mesh.vertices)f<<"vt "<<v.uv[0]<<' '<<v.uv[1]<<'\n';for(const auto& v:o.mesh.vertices)f<<"vn "<<v.normal[0]<<' '<<v.normal[1]<<' '<<v.normal[2]<<'\n';unsigned material=99;for(const auto& t:o.mesh.triangles){if(material!=unsigned(t.material)){material=unsigned(t.material);f<<"usemtl garment"<<material<<'\n';}f<<"f";for(auto i:t.vertices)f<<' '<<i+1<<'/'<<i+1<<'/'<<i+1;f<<'\n';}}
Input LoadFixture(const char* path){
 std::ifstream f(path,std::ios::binary);char magic[8];f.read(magic,8);if(std::string(magic,8)!="JGFX0001")throw std::runtime_error("Measured garment fixture header");std::array<unsigned,6> counts{};f.read((char*)counts.data(),24);Input in;in.frame.lateral={0,-1,0};in.frame.forward={1,0,0};in.frame.up={0,0,1};in.characterEpoch=2;in.topologyRevision=3;in.gravity={0,0,-72};
 auto read=[&](unsigned count,std::vector<Sample>& out){out.resize(count);for(auto& s:out){f.read((char*)s.position.data(),24);f.read((char*)s.normal.data(),24);for(auto& d:s.lineage.donors){unsigned kind;f.read((char*)&kind,4);d.surface=Surface(kind);f.read((char*)&d.vertex,4);f.read((char*)&d.weight,8);}}};read(counts[0],in.waist);read(counts[1],in.opening);read(counts[2],in.anatomy);read(counts[3],in.rearStraps[0]);read(counts[4],in.rearStraps[1]);in.anatomyTriangles.resize(counts[5]);f.read((char*)in.anatomyTriangles.data(),counts[5]*12);if(!f)throw std::runtime_error("Truncated garment fixture");return in;
}
bool Measured(const char* path,const char* exportPath,bool contacts=false){
 auto input=LoadFixture(path);if(contacts){input.bodyContacts={{{2,-7.8,79},{1,-8.2,43},7.2},{{2,7.8,79},{1,8.2,43},7.2}};}Session session;double total=0,worst=0;std::size_t vertices=0;Point root{};for(auto s:input.opening)root=Add(root,s.position);root=Mul(root,1./input.opening.size());auto rest=input.anatomy;
 for(unsigned frame=0;frame<32;frame++){double angle=.3*std::sin(frame*.3),c=std::cos(angle),s=std::sin(angle);for(unsigned i=0;i<rest.size();i++){auto p=Sub(rest[i].position,root);input.anatomy[i].position=Add(root,{p[0]*c-p[1]*s,p[0]*s+p[1]*c,p[2]});}auto begin=std::chrono::steady_clock::now();const auto& output=session.Update(Style::WhiteJockstrap,input);double ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count();total+=ms;worst=std::max(worst,ms);REQUIRE(Valid(output));garment_shape::Measure(input,output);if(contacts&&!output.contactBudgetSatisfied){double minimum=1e100;unsigned worst=0,at=0;for(auto t:output.mesh.triangles)for(auto c:input.bodyContacts){Point p,q;auto distance=detail::TriangleCapsule(output.mesh.vertices[t.vertices[0]].position,output.mesh.vertices[t.vertices[1]].position,output.mesh.vertices[t.vertices[2]].position,c,p,q,output.measuredCircumference*.008*.3);if(distance<minimum){minimum=distance;worst=at;}++at;}std::cerr<<"Measured contact frame="<<frame<<" minimum="<<minimum<<" triangle="<<worst/input.bodyContacts.size()<<" vertex0="<<output.mesh.triangles[worst/input.bodyContacts.size()].vertices[0]<<" count="<<output.mesh.vertices.size()<<" waist="<<input.waist.size()<<" material="<<unsigned(output.mesh.triangles[worst/input.bodyContacts.size()].material)<<" required="<<output.measuredCircumference*.008*.3<<"\n";}if(contacts)REQUIRE(output.contactBudgetSatisfied);if(!frame){vertices=output.mesh.vertices.size();if(exportPath)Export(output,exportPath);}else REQUIRE(vertices==output.mesh.vertices.size());
 }
 // Actual measured envelope must retain shape variation rather than replacing
 // all directions with one ellipsoid. Compare normalized radial extents.
 auto& out=session.Update(Style::WhiteJockstrap,input);Point lo{1e100,1e100,1e100},hi{-1e100,-1e100,-1e100};for(auto a:input.anatomy){auto p=input.frame.Local(a.position);for(unsigned k=0;k<3;k++){lo[k]=std::min(lo[k],p[k]);hi[k]=std::max(hi[k],p[k]);}}double gap=out.measuredCircumference*.008;Point center{(lo[0]+hi[0])*.5,lo[1]-gap,(lo[2]+hi[2])*.5};Point radius{(hi[0]-lo[0])*.5+gap,hi[1]-center[1]+gap,(hi[2]-lo[2])*.5+gap};double minimum=1e100,maximum=0;unsigned base=14*(unsigned(input.waist.size())+1);for(unsigned i=base+1;i<base+1+32*65;i++){auto p=Sub(input.frame.Local(out.mesh.vertices[i].position),center);double d=Length({p[0]/radius[0],p[1]/radius[1],p[2]/radius[2]});minimum=std::min(minimum,d);maximum=std::max(maximum,d);}REQUIRE(maximum/minimum>1.25);std::cerr<<"TIMING actual contacts="<<contacts<<" mean="<<total/32<<" worst="<<worst<<"\n";REQUIRE(total/32<(contacts?60:30));std::cout<<"PASS actual source "<<input.anatomy.size()<<" vertices, 32 moving states, retained bulges ratio "<<maximum/minimum<<", mean "<<total/32<<"ms worst "<<worst<<"ms\n";return true;
}
int main(int argc,char** argv){try{if(argc>2&&std::string(argv[1])=="--fixture")return Measured(argv[2],argc>3?argv[3]:nullptr,argc>4&&std::string(argv[4])=="--capsules")?0:1;if(argc>1){Session s;Export(s.Update(Style::WhiteJockstrap,Fixture(argc>2?std::stod(argv[2]):1)),argv[1]);return 0;}return Stress()&&Collision()&&Covariance()&&Rejection()?0:1;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 2;}}
