#include <malemod/garments/geometry_export.hpp>
#include <sstream>
#include <iostream>
#include <limits>
using namespace malemod::garments;
static void Check(bool b,const char* m){if(!b)throw std::runtime_error(m);}
template<class F> void Reject(F fn){bool failed=false;try{fn();}catch(const std::exception&){failed=true;}Check(failed,"Invalid source export accepted");}
int main(){try{
 Mesh mesh;for(Point p:std::vector<Point>{{.12345678901234567,0,0},{0,1,0},{0,0,1}}){Vertex v;v.position=p;v.normal={1,0,0};v.uv={.12345678901234567,.5};mesh.vertices.push_back(v);}mesh.triangles.push_back({{0,1,2},MaterialSlot::BlueStripe});
 std::ostringstream obj;geometry_export::WriteOBJ(obj,mesh);std::istringstream lines(obj.str());std::string line;unsigned vi=0,uv=0,norm=0,faces=0;while(std::getline(lines,line)){std::istringstream in(line);std::string kind;in>>kind;if(kind=="v"){Point p;in>>p[0]>>p[1]>>p[2];Check(p==mesh.vertices.at(vi++).position,"OBJ position precision lost");}else if(kind=="vt"){std::array<double,2> p;in>>p[0]>>p[1];Check(p==mesh.vertices.at(uv++).uv,"OBJ UV precision lost");}else if(kind=="vn"){Point p;in>>p[0]>>p[1]>>p[2];Check(p==mesh.vertices.at(norm++).normal,"OBJ normal lost");}else if(kind=="g")Check(line=="g material3","Actual material enum lost");else if(kind=="f"){Check(line=="f 1/1/1 2/2/2 3/3/3","OBJ correspondence changed");faces++;}}
 Check(vi==3&&uv==3&&norm==3&&faces==1,"Incomplete source OBJ");
 MaterialLayout layout;layout.revision=2;layout.jointRevision=1;layout.measuredCircumference=1.2345678901234567;layout.bandThicknessNormalized=.003;layout.upperArcRadians=1.4;layout.sheet={3,32,64};layout.sheetFaces={12,4096};layout.sideBoundary[0]={3,68};AuthoredJoint j;j.name="hem-0-top";j.a={{1,2},{.5,.5}};j.b={{0},{1}};j.restOffset={0,.0015,0};layout.authoredJoints.push_back(j);std::ostringstream json;geometry_export::WriteLayout(json,layout);
 Check(json.str().find("\"offsetProvenance\":\"authored-thickness-contract\"")!=std::string::npos,"Authoritative provenance missing");Check(json.str().find("\"vertices\":[1,2],\"weights\":[0.5,0.5]")!=std::string::npos,"Sewn correspondence changed");Check(json.str().find("\"faceCount\":4096")!=std::string::npos,"Sheet range missing");
 auto defaultKey=std::string("\"sideCoverageExtra\":");auto defaultAt=json.str().find(defaultKey);Check(defaultAt!=std::string::npos,"Default side coverage refinement missing");Check(std::stod(json.str().substr(defaultAt+defaultKey.size()))==.45&&layout.sideCoverageExtra==.45,"Default requested side coverage maximum changed");
 auto refined=layout;refined.sideCoverageExtra=.3;std::ostringstream extra;geometry_export::WriteLayout(extra,refined);auto start=extra.str().find("\"sideCoverageExtra\":");Check(start!=std::string::npos,"Explicit refinement missing");start+=std::string("\"sideCoverageExtra\":").size();Check(std::stod(extra.str().substr(start))==refined.sideCoverageExtra,"Refinement precision lost");
 for(double bad:std::vector<double>{-.001,1.5001,std::numeric_limits<double>::quiet_NaN(),std::numeric_limits<double>::infinity()}){auto invalidExtra=layout;invalidExtra.sideCoverageExtra=bad;Reject([&]{std::ostringstream out;geometry_export::WriteLayout(out,invalidExtra);});}
 refined.sideCoverageAspect=1.375;refined.sideCoverageEffective=.15;std::ostringstream active;geometry_export::WriteLayout(active,refined);for(const auto& item:std::vector<std::pair<std::string,double>>{{"sideCoverageAspect",refined.sideCoverageAspect},{"sideCoverageEffective",refined.sideCoverageEffective}}){auto key="\""+item.first+"\":";auto at=active.str().find(key);Check(at!=std::string::npos,"Measured refinement metadata missing");Check(std::stod(active.str().substr(at+key.size()))==item.second,"Measured refinement precision lost");}
 for(double bad:std::vector<double>{-.001,std::numeric_limits<double>::quiet_NaN(),std::numeric_limits<double>::infinity()}){auto invalidAspect=layout;invalidAspect.sideCoverageAspect=bad;Reject([&]{std::ostringstream out;geometry_export::WriteLayout(out,invalidAspect);});}
 for(double bad:std::vector<double>{-.001,.3001,std::numeric_limits<double>::quiet_NaN(),std::numeric_limits<double>::infinity()}){auto invalidEffective=refined;invalidEffective.sideCoverageEffective=bad;Reject([&]{std::ostringstream out;geometry_export::WriteLayout(out,invalidEffective);});}
 auto invalid=mesh;invalid.vertices[0].position[1]=std::numeric_limits<double>::quiet_NaN();Reject([&]{std::ostringstream out;geometry_export::WriteOBJ(out,invalid);});invalid=mesh;invalid.triangles[0].vertices[2]=3;Reject([&]{std::ostringstream out;geometry_export::WriteOBJ(out,invalid);});
 auto invalidLayout=layout;invalidLayout.jointRevision=0;Reject([&]{std::ostringstream out;geometry_export::WriteLayout(out,invalidLayout);});invalidLayout=layout;invalidLayout.authoredJoints[0].a.weights={.2,.2};Reject([&]{std::ostringstream out;geometry_export::WriteLayout(out,invalidLayout);});invalidLayout=layout;invalidLayout.authoredJoints[0].restOffset[0]=std::numeric_limits<double>::infinity();Reject([&]{std::ostringstream out;geometry_export::WriteLayout(out,invalidLayout);});
 std::ostringstream broken;broken.setstate(std::ios::badbit);Reject([&]{geometry_export::WriteOBJ(broken,mesh);});std::cout<<"PASS exact positions/UV/normals/material/index correspondence, authored finite offsets, malformed/write-failure rejection\n";return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
