#include <malemod/garments/jockstrap.hpp>
#include <malemod/garments/sewn_contact.hpp>
#include <iostream>
using namespace malemod::garments;
struct Seam{unsigned count=0;std::array<unsigned,8>nodes{};std::array<double,8>weights{};};
void Require(bool value,const char*message){if(!value)throw std::runtime_error(message);}
int main(){try{
 std::vector<double> inverseMass{1,2,3,0};std::vector<Point> positions{{0,0,0},{1,0,0},{0,2,0},{0,0,3}};
 std::vector<Seam> seams{{2,{0,1},{1,-1}},{3,{1,2,3},{1,-.5,-.5}},{2,{0,1},{2,-2}}};
 sewn_contact::Projector operatorP(inverseMass,seams);render_contact::Gradient raw;raw.count=1;raw.nodes[0]=0;raw.values[0]={.3,.6,.7};auto projected=operatorP.Filter(raw,positions,inverseMass);std::vector<Point> change(4);for(auto e:projected.entries)change[e.node]=Mul(e.gradient,inverseMass[e.node]);
 for(auto seam:seams){Point residual{};for(unsigned k=0;k<seam.count;k++)residual=Add(residual,Mul(change[seam.nodes[k]],seam.weights[k]));Require(Length(residual)<1e-12,"Projected contact opens sewn stitch");}
 Require(Length(change[3])==0,"Pinned particle moved");double work=Dot(raw.values[0],change[0]);Require(std::abs(work-projected.inverseMass)<1e-12,"Sewn contact effective mass violates virtual work");Require(projected.inverseMass>0,"Valid sewn contact lost freedom");
 render_contact::Gradient null;null.count=2;null.nodes={0,1};null.values[0]={1,0,0};null.values[1]={-1,0,0};Require(operatorP.Filter(null,positions,inverseMass).inverseMass<1e-24,"Pure stitch load produced forbidden displacement");
 Point impulse{},moment{};for(auto e:projected.entries){impulse=Add(impulse,Mul(change[e.node],1/inverseMass[e.node]));moment=Add(moment,Cross(positions[e.node],Mul(change[e.node],1/inverseMass[e.node])));}Require(Length(Sub(impulse,projected.impulse))<1e-12&&Length(Sub(moment,projected.moment))<1e-12,"Measured free-node load or moment mismatches projection");
 auto rotate=[](Point p){return Point{-p[1],p[2],-p[0]};};Point shift{1000,-900,800};auto translated=positions;for(auto&p:translated)p=Add(Mul(rotate(p),100),shift);auto rotatedRaw=raw;rotatedRaw.values[0]=rotate(raw.values[0]);auto transformed=operatorP.Filter(rotatedRaw,translated,inverseMass);Require(std::abs(transformed.inverseMass-projected.inverseMass)<1e-12,"Sewn contact inverse mass changed under rigid frame/unit change");for(unsigned k=0;k<projected.entries.size();k++)Require(Length(Sub(rotate(projected.entries[k].gradient),transformed.entries[k].gradient))<1e-12,"Sewn gradient changed under rigid frame rotation");auto expectedMoment=Add(Mul(rotate(projected.moment),100),Cross(shift,rotate(projected.impulse)));Require(Length(Sub(expectedMoment,transformed.moment))<1e-10,"Sewn nodal moment lost affine-origin covariance");
 auto scaledMass=inverseMass;for(auto&m:scaledMass)m*=100;sewn_contact::Projector massP(scaledMass,seams);auto massScaled=massP.Filter(raw,positions,scaledMass);Require(std::abs(massScaled.inverseMass-100*projected.inverseMass)<1e-10,"Sewn effective mass lost calibrated mass covariance");
 std::vector<double> manyMass(128,1);std::vector<Point> manyPositions(128);std::vector<Seam> chain;for(unsigned i=1;i<128;i++){manyMass[i]=1+double(i)/100;manyPositions[i]={double(i),double(i%3),0};chain.push_back({2,{i-1,i},{1,-1}});}sewn_contact::Projector connected(manyMass,chain);auto full=connected.Filter(raw,manyPositions,manyMass);Require(full.entries.size()==128,"Expanded sewn support was truncated");std::vector<Point> manyChanges(128);for(auto e:full.entries)manyChanges[e.node]=Mul(e.gradient,manyMass[e.node]);for(auto seam:chain)Require(Length(Sub(manyChanges[seam.nodes[0]],manyChanges[seam.nodes[1]]))<1e-12,"Cached projector column opens connected stitch");Require(std::abs(Dot(raw.values[0],manyChanges[0])-full.inverseMass)<1e-12,"Cached expanded virtual work mismatch");
 bool rejected=false;auto invalidMass=manyMass;invalidMass[7]=NAN;try{sewn_contact::Projector invalid(invalidMass,chain);}catch(const std::invalid_argument&){rejected=true;}Require(rejected,"Nonfinite mass accepted");rejected=false;invalidMass=manyMass;invalidMass[0]=2;try{connected.Filter(raw,manyPositions,invalidMass);}catch(const std::invalid_argument&){rejected=true;}Require(rejected,"Changed contact mass accepted without operator rebuild");
 rejected=false;invalidMass=manyMass;invalidMass[0]=0;try{connected.Filter(raw,manyPositions,invalidMass);}catch(const std::invalid_argument&){rejected=true;}Require(rejected,"Changed pinning accepted without operator rebuild");
 auto invalidSeams=chain;invalidSeams[0].weights[0]=NAN;rejected=false;try{sewn_contact::Projector invalid(manyMass,invalidSeams);}catch(const std::invalid_argument&){rejected=true;}Require(rejected,"Nonfinite stitch weight accepted");
 invalidSeams=chain;invalidSeams[0].weights[0]=1e300;rejected=false;try{sewn_contact::Projector invalid(manyMass,invalidSeams);}catch(const std::invalid_argument&){rejected=true;}Require(rejected,"Overflowing weighted stitch accepted");
 auto invalidPositions=manyPositions;invalidPositions[100]={NAN,0,0};rejected=false;try{connected.Filter(raw,invalidPositions,manyMass);}catch(const std::invalid_argument&){rejected=true;}Require(rejected,"Nonfinite expanded support position accepted");
 std::cout<<"PASS cached projector columns,128-node expanded support, rank-redundant stitch, pinned mass, virtual work, actual nodal impulse/moment, frame/length/mass covariance and finite mass/stitch/support validation\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what();return 1;}}
