"""Reproduce the portable clinical sequence from the immutable Wolverine import."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'legacy/wolverine/src/runtime'
DEST=ROOT/'include/malemod/clinical'
FILES=['teaching_sequence.h','fluid_types.h','clear_strand.h','thread_mesh.h','viscous_thread.h','teaching_volume.h','fluid_splat_model.h','teaching_audio.h']

def replace(text,old,new):
    if old not in text: raise ValueError(f'Expected source fragment missing: {old}')
    return text.replace(old,new)

def generate(name):
    text=(SOURCE/name).read_text()
    if name=='teaching_audio.h':
        cue=text[text.index(' static float Cue('):text.index('\n void Begin()',text.index(' static float Cue('))]
        crossing=text[text.index(' bool Crossing('):text.index('\n void Advance(',text.index(' bool Crossing('))]
        return '''#pragma once
// Generated by tools/extract_clinical.py; preserves original cue timing.
#include "common.hpp"
#include "teaching_sequence.h"
namespace malemod::clinical::teaching {
struct AudioCues {
 bool fired[2]{},active=false;
 std::function<void(unsigned)> playPhase;
'''+cue+'\n'+crossing+'''
 void Begin(){fired[0]=fired[1]=false;active=true;}
 void End(){active=false;}
 void Advance(float previous,float current){for(int phase=0;phase<2;phase++)if(Crossing(phase,previous,current)){
  fired[phase]=true;if(playPhase)playPhase(unsigned(phase));
 }}
};
}
'''
    text=replace(text,'#pragma once','#pragma once\n// Generated by tools/extract_clinical.py; see provenance/clinical.json.\n#include "common.hpp"')
    text=text.replace('namespace teaching {','namespace malemod::clinical::teaching {').replace('namespace volumeFluid {','namespace malemod::clinical::volumeFluid {')
    if name=='teaching_sequence.h':
        text=replace(text,'static float sequenceEnd=20.f;','// Each Timeline carries its own sequence end.')
        text=replace(text,'bool active=false; double time=0;','bool active=false; double time=0; float endTime=20.f;')
        text=text.replace('sequenceEnd','endTime')
    if name=='fluid_types.h':
        start=text.index('typedef bool (*CollisionSweep)')
        end=text.index('struct CollisionPath',start)
        text=text[:start]+'''enum class SweepResult { miss, hit, deferred };
struct CollisionQuery {
 std::function<SweepResult(V3,V3,float,FluidImpact&)> callback;
};
'''+text[end:]
        text=replace(text,'bool Sweep(V3 old,V3 next,float radius,FluidImpact& hit){','bool Sweep(V3 old,V3 next,float radius,FluidImpact& hit,CollisionQuery& query){')
        text=replace(text,'collisionDeferred=false;\n  bool found=collisionSweep&&collisionSweep(from,next,radius,hit);\n  pending=!found&&collisionDeferred;return found;',
                     'auto result=query.callback?query.callback(from,next,radius,hit):SweepResult::miss;\n  pending=result==SweepResult::deferred;return result==SweepResult::hit;')
        text=replace(text,'static Settings config;','// Configuration belongs to each Fluid instance.')
    if name in {'clear_strand.h','viscous_thread.h'}:
        text=replace(text,'std::vector<volumeFluid::FluidImpact>* impacts=nullptr)',
                     'std::vector<volumeFluid::FluidImpact>* impacts,volumeFluid::CollisionQuery& query)')
        text=text.replace('volumeFluid::collisionSweep','query.callback')
        if name=='clear_strand.h':text=replace(text,'paths[i].Sweep(old[i],p[i],.08f,hit)','paths[i].Sweep(old[i],p[i],.08f,hit,query)')
        else:text=replace(text,'nodes[i].path.Sweep(old,nodes[i].p,radius,exactHit)','nodes[i].path.Sweep(old,nodes[i].p,radius,exactHit,query)')
        # Collider count can no longer have a default before explicit query args.
        text=text.replace('int colliderCount=8,','int colliderCount,')
    if name=='teaching_volume.h':
        text=replace(text,'volumeFluid::Settings settings;std::string error;',
                     'volumeFluid::Settings settings;volumeFluid::CollisionQuery collisionQuery;float endTime=20.f;std::string error;')
        text=replace(text,'bool Prepare(){settings=volumeFluid::config;','bool Prepare(){')
        text=replace(text,'origin,&impacts);','origin,&impacts,collisionQuery);')
        text=replace(text,'volumeFluid::collisionCount,&impacts);','volumeFluid::collisionCount,&impacts,collisionQuery);')
        text=text.replace('sequenceEnd=','endTime=')
    if name=='fluid_splat_model.h':
        text=replace(text,'#include "fluid_splat_bakes.h"','#include "splat_bakes.hpp"\n#include "fluid_types.h"')
        text=replace(text,'struct SplatModel {','struct SplatModel {\n SplatBakes splatBakes;')
        text=replace(text,'static void Deposit(', 'void Deposit(')
        text=replace(text,'bool (*project)(const FluidImpact&,V3,FluidImpact&)=nullptr;',
                     'std::function<bool(const FluidImpact&,V3,FluidImpact&)> project;')
        text=replace(text,'bool (*resolve)(const FluidImpact&,V3&,V3&)=nullptr;',
                     'std::function<bool(const FluidImpact&,V3&,V3&)> resolve;')
        text=text.replace('DWORD','std::uint32_t').replace('LONG(','std::int32_t(')
    # Each header can be included independently; dependencies remain explicit.
    if name in {'clear_strand.h','viscous_thread.h'}:
        text=replace(text,'#include "common.hpp"','#include "common.hpp"\n#include "fluid_types.h"\n#include "teaching_sequence.h"\n#include "thread_mesh.h"')
    if name=='thread_mesh.h':text=replace(text,'#include "common.hpp"','#include "common.hpp"\n#include "teaching_sequence.h"')
    return text.rstrip()+'\n'

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    records=[]
    for name in FILES:
        content=generate(name);path=DEST/name
        if args.check:
            if not path.exists() or path.read_bytes()!=content.encode(): raise SystemExit(f'Generated file differs: {path}')
        else:path.write_text(content,encoding='utf-8',newline='\n')
        records.append({'source':'legacy/wolverine/src/runtime/'+name,'sourceSHA256':hashlib.sha256((SOURCE/name).read_bytes()).hexdigest(),
                        'path':path.relative_to(ROOT).as_posix(),'sha256':hashlib.sha256(content.encode()).hexdigest()})
    report={'contractVersion':1,'sourceCommit':json.loads((ROOT/'provenance/wolverine.json').read_text())['commit'],'files':records,
            'changes':['engine-neutral namespace and includes','per-instance settings and sequence end','per-instance collision callbacks with deferred result','per-instance deposition state and standard integer timestamps','standard binary bake loading replaces Windows resources'],
            'bakeAsset':'legacy/wolverine/src/runtime/splat_bakes.bin','bakeSHA256':hashlib.sha256((SOURCE/'splat_bakes.bin').read_bytes()).hexdigest(),
            'scope':'Existing clinical simulation, without new physiological behavior or engine rendering.'}
    report_path=ROOT/'provenance/clinical.json'
    rendered=json.dumps(report,indent=2)+'\n'
    if args.check:
        if report_path.read_bytes()!=rendered.encode():raise SystemExit('Clinical provenance differs')
    else:report_path.write_text(rendered,encoding='utf-8',newline='\n')
    print('PASS: portable clinical extraction matches source recipe.' if args.check else 'Extracted eight portable clinical modules.')

if __name__=='__main__':main()
