# Optional, pinned numerical backend. No game, GPU, CUDA or graphics SDK.
set(MALEMOD_NVCLOTH_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/build/dependencies/NvCloth" CACHE PATH "NvCloth checkout")
execute_process(COMMAND git -C "${MALEMOD_NVCLOTH_ROOT}" rev-parse HEAD OUTPUT_VARIABLE nv_revision OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE nv_git)
if(NOT nv_git EQUAL 0 OR NOT nv_revision STREQUAL "6e86b1838ae185c527744d475d34777ff69c1b8a")
  message(FATAL_ERROR "NvCloth CPU requires pinned revision 6e86b1838ae185c527744d475d34777ff69c1b8a")
endif()
execute_process(COMMAND git -C "${MALEMOD_NVCLOTH_ROOT}" diff --quiet HEAD RESULT_VARIABLE nv_dirty)
if(NOT nv_dirty EQUAL 0)
  message(FATAL_ERROR "NvCloth dependency has tracked changes; restore the exact pinned source before building")
endif()
set(nv "${MALEMOD_NVCLOTH_ROOT}/NvCloth")
set(nv_sources Allocator Callbacks Factory PhaseConfig SwCloth SwClothData SwCollision SwFabric SwFactory SwInterCollision SwSelfCollision SwSolver SwSolverKernel TripletScheduler)
list(TRANSFORM nv_sources PREPEND "${nv}/src/")
list(TRANSFORM nv_sources APPEND ".cpp")
list(APPEND nv_sources "${nv}/include/NvCloth/ps/PsAllocator.cpp" "${nv}/src/avx/SwSolveConstraints.cpp")
foreach(extension ClothFabricCooker ClothGeodesicTetherCooker ClothMeshQuadifier ClothSimpleTetherCooker)
  list(APPEND nv_sources "${nv}/extensions/src/${extension}.cpp")
endforeach()
if(WIN32)
  list(APPEND nv_sources "${nv}/src/ps/windows/PsWindowsAtomic.cpp")
else()
  list(APPEND nv_sources "${nv}/src/ps/unix/PsUnixAtomic.cpp")
endif()
add_library(malemod_nvcloth_cpu STATIC ${nv_sources})
target_include_directories(malemod_nvcloth_cpu PUBLIC "${nv}/include" "${nv}/extensions/include" "${MALEMOD_NVCLOTH_ROOT}/PxShared/include" PRIVATE "${nv}/src" "${nv}/extensions/src")
target_compile_definitions(malemod_nvcloth_cpu PUBLIC NV_CLOTH_IMPORT= NV_CLOTH_ENABLE_CUDA=0 NV_CLOTH_ENABLE_DX11=0)
target_compile_features(malemod_nvcloth_cpu PRIVATE cxx_std_17)
target_include_directories(malemod_nvcloth_cpu PUBLIC "${CMAKE_CURRENT_LIST_DIR}/nvcloth-compat")
if(MSVC)
  set_source_files_properties("${nv}/src/avx/SwSolveConstraints.cpp" PROPERTIES COMPILE_OPTIONS /arch:AVX)
  target_compile_options(malemod_nvcloth_cpu PRIVATE /fp:precise /wd4267 /wd4244 /wd4996)
  set_property(TARGET malemod_nvcloth_cpu PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
else()
  set_source_files_properties("${nv}/src/avx/SwSolveConstraints.cpp" PROPERTIES COMPILE_OPTIONS -mavx)
endif()
