#pragma once
// Generated by tools/extract_clinical.py; preserves original cue timing.
#include "common.hpp"
#include "teaching_sequence.h"
namespace malemod::clinical::teaching {
struct AudioCues {
 bool fired[2]{},active=false;
 std::function<void(unsigned)> playPhase;
 static float Cue(int phase){return phase==0?peaks[0]+1.f:peaks[4];}
 bool Crossing(int phase,float previous,float current)const{return active&&!fired[phase]&&previous<Cue(phase)&&current>=Cue(phase);}
 void Begin(){fired[0]=fired[1]=false;active=true;}
 void End(){active=false;}
 void Advance(float previous,float current){for(int phase=0;phase<2;phase++)if(Crossing(phase,previous,current)){
  fired[phase]=true;if(playPhase)playPhase(unsigned(phase));
 }}
};
}
